import os

NPC_MARKET_ENABLED = os.getenv("NPC_MARKET_ENABLED", "1").strip().lower() in ("1", "true", "yes")
NPC_MARKET_TICK_HOURS = float(os.getenv("NPC_MARKET_TICK_HOURS", "6"))
NPC_PRESENCE_INTERVAL_SEC = int(os.getenv("NPC_PRESENCE_INTERVAL_SEC", "480"))
NPC_SHOP_COUNT = int(os.getenv("NPC_SHOP_COUNT", "6"))

MAX_ACTIVE_LISTINGS_PER_NPC = 10
TARGET_ACTIVE_LISTINGS_MIN = 6
TARGET_ACTIVE_LISTINGS_MAX = 8
INITIAL_INVENTORY_SIZE = 14
INITIAL_SHOWCASE_COUNT = 3
INITIAL_LISTINGS_MIN = 6
INITIAL_LISTINGS_MAX = 8

DAILY_ACTION_BUDGET_MIN = 6
DAILY_ACTION_BUDGET_MAX = 12
STALE_LISTING_DAYS_MIN = 10
STALE_LISTING_DAYS_MAX = 14

NPC_TREASURY_CASH = 500_000
FAKE_ITEM_RATE = 0.02

# 排行榜拟真波动：每日一次较明显变化 + 在线刷新时微量抖动
NPC_DRIFT_DAILY_CASH_RATE = float(os.getenv("NPC_DRIFT_DAILY_CASH_RATE", "0.042"))
NPC_DRIFT_DAILY_PROFIT_SPREAD = int(os.getenv("NPC_DRIFT_DAILY_PROFIT_SPREAD", "2200"))
NPC_DRIFT_MICRO_CASH_RATE = float(os.getenv("NPC_DRIFT_MICRO_CASH_RATE", "0.0022"))
